version: '3.7'
services:

  mysqldb:
    image: mysql:8.0.18
    ports:
      - '3306:3306'
    volumes:
      - ./src/test/resources:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgres:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass

    ports:
      - '5432:5432'

    volumes:
      - ./db_postgres:/var/lib/postgresql

  node-app:
    build: gate-simulator
    image: node-app:1.0
    container_name: node
    ports:
      - '9999:9999'
